### ISSUE TITLE
Add Release 4.2.0 to Bower

### ISSUE THREAD

**Issue by drubarth** [angular-pouchdb/angular-pouchdb#101]
The instructions describe using Bower to install, but version 4.2.0 is not yet in Bower.  Could you add the latest release to Bower since if fixes some bugs.
thanks,
Darryl

**Comment by tlvince** [comment]
Thanks for the heads up. Sounds like something's up with the continuous deploy script.

**Comment by gimox** [comment]
+1

**Comment by sjaakieb** [comment]
+1

**Comment by tlvince** [comment]
https://github.com/angular-pouchdb/bower-angular-pouchdb/commit/2539fa2950dbdbcdaf039129abecdd73602a7c4c.
