### ISSUE TITLE
Question: How to use angular-pouchdb to add community plugins?

### ISSUE THREAD

**Issue by YanMagale** [angular-pouchdb/angular-pouchdb#108]
Hi all!

I want to use [Pouchdb Adapter Cordova Sqlite](https://github.com/nolanlawson/pouchdb-adapter-cordova-sqlite), but when i called in my provider:

```pouchDB.plugin()```, i received the error message: plugin function is not defined.

How you makes for use community plugins using the angular-pouchdb?

**Comment by tlvince** [comment]
`.plugin` is a constructor method, not instance method. Try something like:

```js
$window.PouchDB.plugin(myPlugin)
```
