### ISSUE TITLE
pouchdb 6 support

### ISSUE THREAD

**Issue by ponyesteves** [angular-pouchdb/angular-pouchdb#109]
Hi, have someone test it with pouchdb v6. Is compatible?

**Comment by tomchiverton** [comment]
In some very basic tests in Chrome, get(), put() and remove() all work with v6

**Comment by ponyesteves** [comment]
Ok. I'll give it a try a and comment post feedback!
thanks

**Comment by tomchiverton** [comment]
Also appears fine on iOS, Android and Windows Phone 8 via PhoneGap 
-- 
Tom
