### ISSUE TITLE
db(...).createIndex is not a function

### ISSUE THREAD

**Issue by MichelMiola** [angular-pouchdb/angular-pouchdb#113]
# Hello! 👋

The function to create an index is not being found.

**Comment by tlvince** [comment]
`createIndex` sounds like a [pouchdb-find](https://github.com/nolanlawson/pouchdb-find) method. You need to manually handle [plugins](https://github.com/angular-pouchdb/angular-pouchdb/tree/98d8eaa66a333cc837ad373dcae75dbf5ba942b4#does-this-work-with-pouchdb-plugins).
