### ISSUE TITLE
Don't depend on a concrete version of pouchdb

### ISSUE THREAD

**Issue by alxndrsn** [angular-pouchdb/angular-pouchdb#114]
At https://github.com/angular-pouchdb/angular-pouchdb/blob/master/package.json#L40, the version of pouchdb is hardcoded.  It would be helpful for this version to instead be a minimum, e.g. `^6.0.7`, to allow tools such as browserify to deduplicate the dependency for projects which also reference `pouchdb-browser` or `pouchdb` as a separate dependency.

**Comment by tlvince** [comment]
Closed by #115.
