### ISSUE TITLE
Need support for angular 2 ? 

### ISSUE THREAD

**Issue by lakinmohapatra** [angular-pouchdb/angular-pouchdb#116]
Hi ,
We all need support for angular 2 + 

Please add it if possible. 

Thanks

**Comment by tlvince** [comment]
https://github.com/angular-pouchdb/angular-pouchdb/issues/94
https://github.com/angular-pouchdb/angular-pouchdb#does-this-work-with-angular-v2

**Comment by lakinmohapatra** [comment]
Thanks for your confirmation .
