### ISSUE TITLE
Breaks on minification

### ISSUE THREAD

**Issue by jpike88** [angular-pouchdb/angular-pouchdb#117]
I needed to run ng-annotate on this file to uglify it properly. Probably a good idea to add annotation to the build process.

**Comment by jpike88** [comment]
Checking package.json shows that annotation is already built in... someone screwed up on the latest release I think.

**Comment by tlvince** [comment]
Releases are automated. Please use the [bower repo](https://github.com/angular-pouchdb/bower-angular-pouchdb) if you'd like to use the built/annotated version. Thanks!

**Comment by jpike88** [comment]
Your previous versions used to be annotated and built in your repo, ready to go. So it's actually gotten worse in that regard.

Dependency managers are there to facilitate easy deployment, but shouldn't be treated as a CDN. 

So no, I'll stick to annotating it directly instead of using bower just for angular-pouchdb, this is the first library that requires I use bower just to get at a functional copy. Not good.
