### ISSUE TITLE
Publish to Bower registry

### ISSUE THREAD

**Issue by tlvince** [angular-pouchdb/angular-pouchdb#21]
Right now, we instruct users to install via a shorthand GitHub link.

Searching for "angular-pouchdb" on the Bower registry today yields:

```shell
❯  bower search angular-pouchdb
Search results:

    angular-pouchdb git://github.com/wspringer/angular-pouchdb.git
    angular-pouchdb2 git://github.com/angular-pouchdb/angular-pouchdb.git
```

Since the last published version of @wspringer's angular-pouchdb is [0.1.6-SNAPSHOT](https://github.com/wspringer/angular-pouchdb/blob/82d05518274888d156249a5ace26c05eeae1edf3/bower.json#L3), AFAIK, if the original was [unregistered](http://bower.io/docs/creating-packages/#unregister) and reregistered under this repo, people who've already included `angular-pouchdb` in their `bower.json` will pull in the latest on their next `bower install`? I'm not sure what'll happen about [previous releases](https://github.com/wspringer/angular-pouchdb/commits/master/bower.json) though (should I "backdate" those tags?).

:+1:/:-1: on this?

NB, I don't know where angular-pouchdb2 has come from or who owns it.

**Comment by gustavohenke** [comment]
Hey @tlvince,
Who registered `angular-pouchdb2` is an mystery, however, _you_ are the owner of the repository.
Therefore, you're able to unregister it.

Also, people who do currently depend on `angular-pouchdb` will install the package from here in their next `bower install` if @wspringer's repository is unregistered.
The only problem is that bower may spit errors because of the unknown version range.

**Comment by tlvince** [comment]
Ah, cool. I wasn't aware the owner of the linked repo could unpublish it. Is there a way find out who created it originally so I can give them a heads up before I do?

Re "unknown version range", perhaps we could try it first against a test repo?

**Comment by gustavohenke** [comment]
The errors I mentioned are because of people referencing `0.x` range, while this repo started at `1.x`.

About discovering who registered the repo, I don't know if it's currently possible.
