### ISSUE TITLE
Add test coverage reporting

### ISSUE THREAD

**Issue by tlvince** [angular-pouchdb/angular-pouchdb#27]
* Istanbul via an npm script
* Coveralls (because, why not?)

**Comment by gustavohenke** [comment]
I like karma-coverage, makes generating lcov very easy.
Then some script to upload data to coveralls on `after_success` callback of Travis.

**Comment by tlvince** [comment]
:+1:

**Comment by tlvince** [comment]
Closed by 724c4e50e335c043106635b1fc9037d553c13e9f.
