### ISSUE TITLE
Publish on npm

### ISSUE THREAD

**Issue by tlvince** [angular-pouchdb/angular-pouchdb#29]

**Comment by angelxmoreno** [comment]
I see the module on npm but the installation fails. It is trying to install bower ?
<img width="892" alt="screen shot 2015-12-09 at 11 46 38 pm" src="https://cloud.githubusercontent.com/assets/363479/11707329/2d5aacc4-9ed1-11e5-8ca7-fc426b565c76.png">

**Comment by tlvince** [comment]
That's a bug in the in our npm scripts block. Surprising no one has caught it until now. Can you open a new issue? Thanks.

**Comment by angelxmoreno** [comment]
:+1:

**Comment by angelxmoreno** [comment]
Created #86 - bug in the npm scripts block
