### ISSUE TITLE
Bower: Package not found

### ISSUE THREAD

**Issue by jchayan** [angular-pouchdb/angular-pouchdb#34]
I'm trying to add this into my bower.json like

{
    "dependencies": {
        "angular-pouchdb/angular-pouchdb": ""
    }
}

But I get:

bower ENOTFOUND     Package angular-pouchdb/angular-pouchdb=angular-pouchdb/angular-pouchdb not found

If I try to install from command line (bower install --save angular-pouchdb/angular-pouchdb)

I get:
bower cached        git://github.com/angular-pouchdb/angular-pouchdb.git#1.0.2
bower validate      1.0.2 against git://github.com/angular-pouchdb/angular-pouchdb.git#*
bower not-cached    git://github.com/angular/bower-angular.git#~1.3.7
bower resolve       git://github.com/angular/bower-angular.git#~1.3.7
bower not-cached    git://github.com/daleharvey/pouchdb.git#~3.2.0
bower resolve       git://github.com/daleharvey/pouchdb.git#~3.2.0
bower download      https://github.com/angular/bower-angular/archive/v1.3.8.tar.gz
bower download      https://github.com/daleharvey/pouchdb/archive/3.2.1.tar.gz
bower progress      pouchdb#~3.2.0 received 0.3MB
bower extract       angular#~1.3.7 archive.tar.gz
bower resolved      git://github.com/angular/bower-angular.git#1.3.8
bower progress      pouchdb#~3.2.0 received 0.3MB
bower progress      pouchdb#~3.2.0 received 0.3MB
bower ENOTFOUND     Package angular-pouchdb/angular-pouchdb=angular-pouchdb/angular-pouchdb not found

Still, can't see the package into my bower_components folder

**Comment by jchayan** [comment]
Well, turns out that the bower registry is located 'angular-pouchdb2'. Update in the readme, please

**Comment by gustavohenke** [comment]
It's not an official package. See #21 

I'm currently referencing the package this way:

```json
"angular-pouchdb": "angular-pouchdb/angular-pouchdb"
```

**Comment by jchayan** [comment]
@gustavohenke Oh great, thanks

**Comment by tlvince** [comment]
Yes, @gustavohenke's method is the way to consume this package right now. You can add a tag if you like:

```
"angular-pouchdb": "angular-pouchdb/angular-pouchdb#1.0.2"
```

#21 will make this easier in the future.
