### ISSUE TITLE
Error: db[parent] is undefined

### ISSUE THREAD

**Issue by jo** [angular-pouchdb/angular-pouchdb#43]
coming from here: https://github.com/angular-pouchdb/angular-pouchdb/blob/master/angular-pouchdb.js#L78

**Comment by tlvince** [comment]
@jo, have you modified `pouchDBProvider.methods` somehow? Otheriwse `Error: db[parent] is undefined` could only occur if PouchDB's public API has changed, i.e. an instance doesn't contain one of [these methods](https://github.com/angular-pouchdb/angular-pouchdb/blob/6f02d69aa01720041fc3d7f80732e960a47582a9/angular-pouchdb.js#L5-L25).

**Comment by jo** [comment]
I have indeed modified the methods (added a method to be angularpromisified) but this is not the problem here I think. The issue occurs with the replication api.

I was able to trace down the issue to the asynchronous creation of PouchDBs API itself (Note that its async only for adapters which needs async init). [Here you can see](https://github.com/pouchdb/pouchdb/blob/master/lib/constructor.js#L99) that the replication API object gets created inside a promise.

Currently I am trying to get around this problem by changing the constructor to
```js
        return new $window.PouchDB(name, options, function(err, db) {
          wrapMethods(db, self.methods);
        });
```

But this introduces other problems: it only works in the browser but the tests fail.
Calling `wrapMethods` twice reads like a hack, but works:
```js
      return function pouchDB(name, options) {
        var db = new $window.PouchDB(name, options, function(err, db) {
          wrapMethods(db, self.methods);
        });
        return wrapMethods(db, self.methods);
      };
```

**Comment by jo** [comment]
I think the clean solution would be to patch PouchDB to support a custom promise constructor as option.

**Comment by tlvince** [comment]
Sounds promising (pun intended). Might also help with #37 (where methods are added *after* instantiation)?

**Comment by jo** [comment]
I don't think this would work, at least not without changing the plugins itself, because most plugins [require their own utils](https://github.com/nolanlawson/relational-pouch/blob/master/lib/index.js#L5).

@nolanlawson I would love to hear your thoughts about providing an overridable `PouchDB.utils.Promise` in particular and about `PouchDB.utils` and their use from within plugins in general.

**Comment by jo** [comment]
Today I cannot reproduce this issue because a) my FF latterly constantly crashes and b) it works in Chrome. So either this was a problem of a dying Firefox or any other, I don't know, although my explanation still sounds reasonable to me...

Feel free to reopen.
