### ISSUE TITLE
Can't unit test in v2.0.0 anymore

### ISSUE THREAD

**Issue by gustavohenke** [angular-pouchdb/angular-pouchdb#57]
Hello @tlvince,
It's been a while since I last contributed to angular-pouchdb!

I'm locally updating [Model](https://github.com/Syonet/model) to use angular-pouchdb 2.x.x.
For some reason, my tests _never_ finish, causing Mocha to timeout. Seems like the PouchDB promises are never invoked after they're passed to `$q.when` (as of #24).

I tried a lot of things to make the promises go on, and none works:
- `$rootScope.$apply()`
- `$rootScope.$applyAsync()`
- `$timeout.flush()`

Any tips?
I know that this may not be related to your library, but I'm asking because you may point me to the right direction.

Thanks in advance!

**Comment by nolanlawson** [comment]
@gustavohenke Which version of PouchDB are you using? We changed our promise implementation in 4.0.0.

**Comment by gustavohenke** [comment]
@nolanlawson I use the one depended by angular-pouchdb, which is `^3.6.0` right now.

I just found that if you inject `ngMock` module, then those promises will start to fail.
I cloned angular-pouchdb, and injected that module [here](https://github.com/angular-pouchdb/angular-pouchdb/blob/7d5d616b03efb54cc22ddc43fbde2aa9c69de782/test/api.js#L37), and.... tada:

![](http://i.imgur.com/FUIaC3G.png)

**Comment by nolanlawson** [comment]
Hm, did you set a larger async timeout for those tests? We often have to do that in our Mocha tests for PouchDB.

**Comment by gustavohenke** [comment]
Tried 15 seconds, no success.

**Comment by nolanlawson** [comment]
Hm, not sure what to say, then. I'm not very familiar with angular-pouchdb.

**Comment by gustavohenke** [comment]
Previously, my tests worked because angular-pouchdb used PouchDB callbacks instead of promises.
Maybe it's something I'm missing from Angular testing, but let's wait to see if @tlvince has any tips.

**Comment by tlvince** [comment]
@gustavohenke could you try a `beforeEach` block like the following?

```js
  var db;
  beforeEach(function() {
    var $injector = angular.injector(['ng', 'pouchdb']);
    var pouchDB = $injector.get('pouchDB');
    db = pouchDB('db');
  });
```

**Comment by gustavohenke** [comment]
That way things will work because `ngMock` is not injected.
However, I need it, because I'm triggering HTTP requests and timeouts in a few places.

**Comment by tlvince** [comment]
Hmm, honestly, I'm out of ideas. I've ran into similar issues unit testing with `$q.when`. The aforementioned was the only method I found that worked (I'm still not fully sure *why*). I'll do some digging, but will be happy to hear if you come up with something.

**Comment by gustavohenke** [comment]
I dropped a question in StackOverflow: http://stackoverflow.com/questions/32051825/external-promises-never-finish-in-unit-tests-with-ngmock

Let's wait to see if someone knows how to fix that. Otherwise I'll add a bounty.

**Comment by tlvince** [comment]
Thanks!

**Comment by jkrot** [comment]
@tlvince @gustavohenke  After the Recent update that was done for my other issue I can't replicate your issue @gustavohenke 
![unit tests](https://cloud.githubusercontent.com/assets/124587/9335353/282140d8-4599-11e5-8e42-d473568e2f5b.PNG)

**Comment by jkrot** [comment]
So you aren't going to believe the answer for this one,  I am going to commit a fix for it now but basically you had to explicitly imply a done(); in each statement with ngMock.  

  beforeEach(function(done) {
    var $injector = angular.injector(['ng', 'pouchdb', 'ngMock']);
    var pouchDB = $injector.get('pouchDB');
	db = pouchDB('db');
	done();
  });
  
  it('should wrap destroy', function(done) {
	db.destroy()
      .then(shouldBeOK)
      .catch(shouldNotBeCalled)
      .finally(done);
	  done();
  });

Works 100% for me.

**Comment by gustavohenke** [comment]
@jkrot, this can't be the solution.
Jasmine will think that because `done()` was called, that block ended successfully. And then it'll move to the next block (either test or hook).

**Comment by jkrot** [comment]
The first issue was that the beforeEach was never getting completed for the tests. so that was timing out for all of them.  I wen't through and console logged and put in timeouts and even changed the expected values and when I did the tests did fail before the done(); was resolved.  This also works.
<code>
  beforeEach(function(done) {
    var $injector = angular.injector(['ng', 'pouchdb', 'ngMock']);
    var pouchDB = $injector.get('pouchDB');
	db = pouchDB('db');
	done();
  });
  
  it('should wrap destroy', function(done) {
	db.destroy()
      .then(shouldBeOK)
      .catch(shouldNotBeCalled)
      .finally(done());
  });
</code>

**Comment by gustavohenke** [comment]
This will work because `done()` is still being invoked immediately in each test.

**Comment by jkrot** [comment]
K I really don't get it then, adding a parameter in the function for a test makes it a async call
 it('should wrap destroy', function(done) {
    
	db.destroy()
      .then(shouldBeOK)
      .catch(shouldNotBeCalled)
      .finally(done);
  });

If you remove the done from each it just resolves in a sync manner however that promise was resolved by the .then already  all the done() was doing is just resolving it again for the async call you made by adding the parameter

**Comment by jkrot** [comment]
The only one that ever fails for me without ngMock is putAttachment because it can't complete in time and that one actually needs a timeout to let it wait a little bit.

**Comment by jkrot** [comment]
@tlvince do the Unit Tests actually need to be done param for testing?

**Comment by gustavohenke** [comment]
@jkrot, please read the following post: [We have a problem with promises](http://pouchdb.com/2015/05/18/we-have-a-problem-with-promises.html), by @nolanlawson.

**Comment by gustavohenke** [comment]
I placed a bounty of 250 points in that question!

**Comment by jkrot** [comment]
Alright I went back through put a ton of breakpoints in pouchDB which is where the code is dying and watching it die in http://localhost:9876/debug.html as the tests are running, the best I can narrow it down to is line 5849 in pouchdb.js it seems to die in that promise block and never gets out while without ngMock it then goes through hand finishes the promise.
     var promise = new Promise(function (fulfill, reject) {

**Comment by jkrot** [comment]
I updated my stackoverflow answer to better frame how far I got in troubleshooting this, it is clearly a problem with pouchDB from my perspective and an issue should be opened there.

**Comment by tlvince** [comment]
@gustavohenke could try something like the following in your unit tests? https://github.com/angular-pouchdb/angular-pouchdb/compare/multi-digests

**Comment by gustavohenke** [comment]
[Seems to be working](https://travis-ci.org/Syonet/model/builds/77024461) until now!
Amazing tip @tlvince. Don't forget to post it as an answer!

**Comment by gustavohenke** [comment]
@tlvince, the bounty is ending tomorrow, and I'll be traveling, so I won't be able to award it :cry: 

Or maybe @jkrot who engaged very hard in this issue ;)

**Comment by jkrot** [comment]
I will update my answer @tlvince if you dont want it.

**Comment by tlvince** [comment]
Feel free James (I'm currently mobile). NB, I suspect this is necessary due to the fact we have nested promises; $scope.$apply will trigger one digest and therefore resolve one of the promises, but not the other. Also, by handling angular.injector ourselves, we avoid loading ngMock (usually, it'll auto load itself, along with the 'ng' module, see the angular.mocks.module(?) docs), which likely decorates $q or its dependants in someway. That's the hypothesis anyway; it'd be nice if someone could confirm this.

**Comment by jkrot** [comment]
@tlvince Hmm I tried putting in the suggested changes and getting an error TypeError: 'undefined' is not an object (evaluating ' current.$$watchers')  for the suggest unit test.  I also feel like this is more on an issue with ngMock injecting itself since that is where all my console.log traces died at before the timeout finished.  I had myself tried using a $timeout and rootscope.$apply to try to force some digests through but nothing ever seemed to work.  I am trying to see if anyone else has had a similar issue and document it.
