### ISSUE TITLE
npm build scripts are unsupported on Windows

### ISSUE THREAD

**Issue by jkrot** [angular-pouchdb/angular-pouchdb#60]
First time installing this package to try and troubleshoot and issue for another user and I can't even get a npm install to go through I am getting this error.
![buildfailure](https://cloud.githubusercontent.com/assets/124587/9314256/5c39493a-44ed-11e5-898d-30cfb182c515.PNG)

**Comment by jkrot** [comment]
Switching branches to 2.1.0 deleting the node_modules and installing fails as well.

**Comment by gustavohenke** [comment]
That seems to happen because of `prebuild` script. Happens to me as well.

**Comment by jkrot** [comment]
Seems like it was just this specific commit,  https://github.com/angular-pouchdb/angular-pouchdb/commit/cd33e588b5cf305e1e3de391719acd369425c19a  but trying to figure out why older tags are broken as well.

**Comment by jkrot** [comment]
This seems to be a problem in pouchdb created and issue there as well.  https://github.com/pouchdb/pouchdb/issues/4173

**Comment by tlvince** [comment]
I see at the very top `mkdir -p dist` fails, which makes sense as you're running Windows. I'll see what I can do to make the npm scripts OS agnostic. Thanks.

**Comment by tlvince** [comment]
@jkrot could you try 2.1.2? Thanks.

**Comment by jkrot** [comment]
Pulled new brache and works fine now.  Thanks @tlvince
