### ISSUE TITLE
How to integrate with the PouchDB Inspector for Chrome?

### ISSUE THREAD

**Issue by catogonzalez** [angular-pouchdb/angular-pouchdb#63]
I want to be able to use the [Inspector](https://chrome.google.com/webstore/detail/pouchdb-inspector/hbhhpaojmpfimakffndmpmpndcmonkfa) with my PouchDBs. If I don't wrap Pouch with angular-pouchdb I can inspect the DB but when using angular-pouchdb the databases don't show up in the inspector. By the PouchDB Inspector for Chrome extension docs: **"The only requirement is you expose window.PouchDB."**

How can I do this?

**Comment by nolanlawson** [comment]
You could just add PouchDB as a script somewhere; this at least makes it debuggable. E.g.

```html
<script src="http://cdn.jsdelivr.net/pouchdb/latest/pouchdb.min.js"></script>
```

**Comment by catogonzalez** [comment]
Thanks for your reply, @nolanlawson.

I do have PouchDB in my `index.html`:

```javascript
    <script src="lib/pouchdb/dist/pouchdb.min.js"></script>
    <script src="lib/pouchdb-authentication/dist/pouchdb.authentication.min.js"></script>
    <script src="lib/angular-pouchdb/angular-pouchdb.min.js"></script>
```

I believe `angular-pouchdb.min.js` is somehow *hiding* the window.PouchDB object...

**Comment by tlvince** [comment]
angular-pouchdb doesn't do anything special in this regard; it shouldn't be hiding `window.PouchDB`. For example, open the console up on the [docs site](https://angular-pouchdb.github.io/angular-pouchdb/#/). Perhaps something else is conflicting?

**Comment by catogonzalez** [comment]
Thanks for your idea @tlvince. I did go to the docs site and the db shows up well:

<img width="1428" alt="Good result @ docs site" src="https://cloud.githubusercontent.com/assets/5244205/9875073/e42f997c-5b70-11e5-8395-fed9a82c2dcb.png">

But I tried also some of the sample [code links](http://bl.ocks.org/nolanlawson/7c32861af5d31a8fac4a) in [PouchDB's changes documentation](http://pouchdb.com/guides/changes.html) and the db does not show up :( see:

<img width="893" alt="screen shot 2015-09-14 at 7 01 33 am" src="https://cloud.githubusercontent.com/assets/5244205/9875123/3cdaf814-5b71-11e5-98ec-8153adf36a23.png">

I have no idea what's going on :( appreciate any ideas/solution as it will be a huge help for debugging my apps.

**Comment by tlvince** [comment]
The bl.ocks example won't work because it's served via a iFrame; it's fine if you browse to the [raw version](http://bl.ocks.org/nolanlawson/raw/7c32861af5d31a8fac4a/374ea791c045b2d8a9e3bf8bfa4920a267f3edca/). Are you using iFrame's in your app, perhaps?

**Comment by catogonzalez** [comment]
Found the problem! Turns out that when forcing the `websql` adapter the db instance is not visible in PouchDB Inspector; using the default `idb` adapter makes the db instance appear well.

```javascript
var db = new PouchDB('myDB', {adapter: 'websql'}); // does not show
```

```javascript
var db = new PouchDB('myDB'); // shows up perfectly well
```  
Thanks @tlvince and @nolanlawson for your help.

**Comment by tlvince** [comment]
For reference from [pouchdb-fauxton-chrome-extension](https://github.com/pouchdb/pouchdb-fauxton-chrome-extension):

> IndexedDB backed databases are supported only (but that's the default anyway).

I've ran into this [too](https://github.com/pouchdb/pouchdb-fauxton-chrome-extension/issues/1) :smile:. Glad you resolved it.
