### ISSUE TITLE
I think db[parent][method] = wrapFunction(db[parent][method]); should be commented?

### ISSUE THREAD

**Issue by peplamb** [angular-pouchdb/angular-pouchdb#64]
Hi,

Thanks for the great work.

Just a note I had issues in firefox and commented the following line and everythign seems to be working fine.

          db[parent][method] = wrapFunction(db[parent][method]);

Would you please have a look?

Thank you!

**Comment by tlvince** [comment]
That's there to support nested methods, such as the [replicate API](https://github.com/angular-pouchdb/angular-pouchdb/blob/c12e36e43f37d0ecb82c07d83934e1d70284bcb5/angular-pouchdb.js#L22-L25). What issue are you running into specifically?

**Comment by peplamb** [comment]
This is what I am receiving when i uncomment that line in forefox.

![image](https://cloud.githubusercontent.com/assets/875754/9838336/17141b22-5a29-11e5-8868-c80f23ed6380.png)

I am using AngularJS v1.2.20

Thank you,

**Comment by tlvince** [comment]
I'll add Firefox to the test suite and see if I can reproduce.

**Comment by tlvince** [comment]
Can you try updating to Anguar v1.4.x?

I've added Firefox to the test suite, which [passed in Travis](https://travis-ci.org/angular-pouchdb/angular-pouchdb/builds/80226257) (Firefox v31) and [manually tested](https://gist.github.com/tlvince/8e8c11ac8851dfb32b09) (Firefox v40), but couldn't reproduce.

**Comment by tlvince** [comment]
Closing due to lack of response.

**Comment by iron9light** [comment]
Got the same problem with firefox and Edge on Win10
angular-pouch: 4.0.0
angularjs: 1.5.0-rc.0
pouch: 5.1.0

Error: db[parent] is undefined
wrapMethods@http://localhost:8100/lib/angular-pouchdb/angular-pouchdb.js:84:11
wrapMethods@http://localhost:8100/lib/angular-pouchdb/angular-pouchdb.js:73:13
pouchDB@http://localhost:8100/lib/angular-pouchdb/angular-pouchdb.js:91:16
openDb@http://localhost:8100/js/app.js:442:29
@http://localhost:8100/js/app.js:449:25
invoke@http://localhost:8100/lib/angular/angular.js:4657:14
enforcedReturnValue@http://localhost:8100/lib/angular/angular.js:4509:20
invoke@http://localhost:8100/lib/angular/angular.js:4657:14
createInjector/protoInstanceInjector<@http://localhost:8100/lib/angular/angular.js:4469:1
getService@http://localhost:8100/lib/angular/angular.js:4616:39
invoke@http://localhost:8100/lib/angular/angular.js:4648:1
enforcedReturnValue@http://localhost:8100/lib/angular/angular.js:4509:20
invoke@http://localhost:8100/lib/angular/angular.js:4657:14
createInjector/protoInstanceInjector<@http://localhost:8100/lib/angular/angular.js:4469:1
getService@http://localhost:8100/lib/angular/angular.js:4616:39
invoke@http://localhost:8100/lib/angular/angular.js:4648:1
$ControllerProvider/this.$get</</instantiate<@http://localhost:8100/lib/angular/angular.js:9622:24
nodeLinkFn@http://localhost:8100/lib/angular/angular.js:8731:34
compositeLinkFn@http://localhost:8100/lib/angular/angular.js:8035:13
nodeLinkFn@http://localhost:8100/lib/angular/angular.js:8762:1
compositeLinkFn@http://localhost:8100/lib/angular/angular.js:8035:13
nodeLinkFn@http://localhost:8100/lib/angular/angular.js:8762:1
compositeLinkFn@http://localhost:8100/lib/angular/angular.js:8035:13
compositeLinkFn@http://localhost:8100/lib/angular/angular.js:8038:13
compositeLinkFn@http://localhost:8100/lib/angular/angular.js:8038:13
publicLinkFn@http://localhost:8100/lib/angular/angular.js:7915:30
bootstrapApply/<@http://localhost:8100/lib/angular/angular.js:1681:11
$RootScopeProvider/this.$get</Scope.prototype.$eval@http://localhost:8100/lib/angular/angular.js:16554:16
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://localhost:8100/lib/angular/angular.js:16654:20
bootstrapApply@http://localhost:8100/lib/angular/angular.js:1679:9
invoke@http://localhost:8100/lib/angular/angular.js:4657:14
bootstrap/doBootstrap@http://localhost:8100/lib/angular/angular.js:1677:1
bootstrap@http://localhost:8100/lib/angular/angular.js:1697:1
angularInit@http://localhost:8100/lib/angular/angular.js:1591:5
@http://localhost:8100/lib/angular/angular.js:29854:5
jQuery.Callbacks/fire@http://localhost:8100/lib/jquery/dist/jquery.js:3099:10
jQuery.Callbacks/self.fireWith@http://localhost:8100/lib/jquery/dist/jquery.js:3211:7
.ready@http://localhost:8100/lib/jquery/dist/jquery.js:3417:1
completed@http://localhost:8100/lib/jquery/dist/jquery.js:3433:2
consoleLog/<()angular.js (line 13003)
$ExceptionHandlerProvider/this.$get</<()angular.js (line 9732)
$RootScopeProvider/this.$get</Scope.prototype.$apply()angular.js (line 16659)
bootstrapApply()angular.js (line 1679)
invoke()angular.js (line 4657)
bootstrap/doBootstrap()angular.js (line 1677)
bootstrap()angular.js (line 1697)
angularInit()angular.js (line 1591)
angular.js()angular.js (line 29854)
jQuery.Callbacks/fire()jquery.js (line 3099)
jQuery.Callbacks/self.fireWith()jquery.js (line 3211)
.ready()jquery.js (line 3417)
completed()jquery.js (line 3433)
angular.js (line 13003)
