### ISSUE TITLE
pouchDB is not a function

### ISSUE THREAD

**Issue by louisdoe** [angular-pouchdb/angular-pouchdb#72]
Hi

I've installed this library in my angular app : https://github.com/angular-pouchdb/angular-pouchdb (using `ionic add angular-pouchdb`).

But I get this error: `Uncaught ReferenceError: pouchDB is not defined` when I tried to declare a factory that instanciates the database. See my code below.

app.js

    angular.module('BoardLine', ['ionic', 'ngCookies', 'ui.unique', 'pouchdb', 'BoardLine.controllers', 'BoardLine.services', 'BoardLine.filters'])

services.js

    .factory('usersDatabase', [ function(pouchdb) {
    	var usersDatabase = pouchDB('boardline_users');
    	var remote = 'https://louisromain:bingin/*@louisromain.cloudant.com/boardline_users';
    	var opts = {live: true,
    	            retry: true};
    	usersDatabase.replicate.to(remote, opts);
    	usersDatabase.replicate.from(remote, opts);
    	//console.log(usersDatabase);
    	return usersDatabase;
    }])

index.html :

    <script src="lib/angular-pouchdb/angular-pouchdb.js"></script>

If I write ` .factory('usersDatabase', [ function(pouchDB) {` instead (uppercase DB instead of lowercase db),
I get this error: `Uncaught TypeError: pouchDB is not a function`.

**Comment by tlvince** [comment]
If you're using Angular's DI array syntax, you need something like:

```
.factory('usersDatabase', ['pouchDB', function(pouchDB) {
```

**Comment by louisdoe** [comment]
Hi Tivince,

with this I get : Uncaught TypeError: $window.PouchDB is not a function

Can you help me further ?

**Comment by tlvince** [comment]
Make sure you have `PouchDB` sourced in your `index.html` (or however you're managing your dependencies), e.g.:

```
<script src="https://cdn.jsdelivr.net/pouchdb/4.0.3/pouchdb.min.js"></script>
```

**Comment by louisdoe** [comment]
ok in my index.html, I had only reference angular-pouchdb, I just added this line : 

        <script src="lib/pouchdb/dist/pouchdb.js"></script>

and it seems to work  now.

Thanks a lot Tivince.

**Comment by tlvince** [comment]
Sweet!
