### ISSUE TITLE
Will PouchDB 5.0 Break angular-pouchdb?

### ISSUE THREAD

**Issue by FlipOne** [angular-pouchdb/angular-pouchdb#75]
If it will, is a patch for angular-pouchdb coming soon? If not soon, how do we go about doing a temporary fix?

**Comment by tlvince** [comment]
It doesn't break angular-pouchdb. I've just made a new release https://github.com/angular-pouchdb/angular-pouchdb/releases/tag/v4.0.0.

**Comment by FlipOne** [comment]
Thanks Tom, and kudos for your work on PouchDB in general and angular-pouchdb in particular. 

Incidentally, is there any best-practice, open-source or reference implementation app you can recommend (for a pouchdb newbie like myself) that uses the latest, or possibly the latest possible, angular-pouchdb? Would appreciate any feedback on this.
