### ISSUE TITLE
Best-Practice Reference Implementation of angular-pouchdb

### ISSUE THREAD

**Issue by FlipOneDev** [angular-pouchdb/angular-pouchdb#76]
Hi Tom,

Is there any best-practice, open-source or reference implementation app you can recommend (for a pouchdb newbie like myself) that uses the latest, or possibly the latest possible, angular-pouchdb? Would appreciate any feedback on this.

Thanks for your continued contribution to pouchdb and angular-pouchdb.

**Comment by tlvince** [comment]
The thing to remember about angular-pouchdb is that it does very little; it's simply a convenience wrapper over PouchDB that aids integration in Angular projects.

With that in mind, I'd suggest reading [PouchDB](http://pouchdb.com/guides/) and [CouchDB](http://guide.couchdb.org) guides to get up and running. The PouchDB website also mentions [a list of products and services that use PouchDB](http://pouchdb.com/users.html) that may be of help.

We at eHealth Africa use angular-pouchdb in offline-first healthcare applications such as [Move](https://github.com/eHealthAfrica/move) and [Direct Delivery](https://github.com/eHealthAfrica/direct-delivery). @nolanlawson (a core contributor of PouchDB) may also be able to point out specific examples.

Hope that is some use.

**Comment by FlipOneDev** [comment]
@tlvince - appreciate it!
