### ISSUE TITLE
LocalStorage adapter option for Node-Webkit (NW.js) ?

### ISSUE THREAD

**Issue by NLKNguyen** [angular-pouchdb/angular-pouchdb#78]
Thanks for your awesome work,

I wonder if it's possible to do something like this http://pouchdb.com/adapters.html#pouchdb_in_node_js with angular-pouchdb.

Thanks

**Comment by tlvince** [comment]
As in running angular-pouchdb in Node? I haven't tried personally, but its published on [npm](https://www.npmjs.com/package/angular-pouchdb) and Browserify support was added in 643c3c05ce5d5c8b19d21921645028cc90be12ef, so perhaps you could give it a try?

**Comment by NLKNguyen** [comment]
It didn't work if I simply `var db = pouchDB('./my.db');`, the data wouldn't store at the given location.

After exploring a bit, it seems like it's not angular-pouchdb issue because pouchdb itself wouldn't work that way in Node-Webkit either. I can use pouchdb with Node to store the database at any location normally, but not with Node-Webkit. I guess pouchdb just doesn't know it's in a Node when it's used in an Angular controller, which is supposed to be in the browser.
Anyway, I am looking for a single NoSQL file based storage solution, and pouchdb doesn't store data that way, so now I'm heading another direction. 

Thanks for your work :)
