### ISSUE TITLE
Make angular-pouchdb more popular

### ISSUE THREAD

**Issue by johannesjo** [angular-pouchdb/angular-pouchdb#8]
I had a hard time finding this one, mostly because of [wspringers](https://github.com/wspringer/angular-pouchdb) shamefully outdated repository. Would be nice if he at least could provide some link to this more up to date version. Another option could be to tweet it to the angular magazine and to publish it on ng-modules. 

Works nicely, thank you! Wouldn't hurt to provide a little more documentation though...

**Comment by tlvince** [comment]
@johannesjo, I'm tidying up the issue tracker [a bit](https://github.com/angular-pouchdb/angular-pouchdb/issues) and have split the documentation issue into its own task (#22) (NB, perhaps you could have a go at it? :wink:).

**Comment by tlvince** [comment]
On "making this more popular", @wspringer, thanks for the [note](https://github.com/wspringer/angular-pouchdb/commit/f360c6f0e3e2aa5a8f1224313cd860b3cc54f7f8). That should help direct some people who're coming via the first result of Google.

@johannesjo, perhaps you could try tweeting/publishing to ng-modules as you suggested?

I noticed "[Update angular-pouchdb link to new fork](https://github.com/pouchdb/pouchdb/issues/3231)" on the PouchDB issue tracker, which will help.

Other suggestions welcome :smile:.

**Comment by tlvince** [comment]
#21 should also help.

**Comment by johannesjo** [comment]
@tlvince first working week here, so I can't promise anything for now, but I will try :)

**Comment by johannesjo** [comment]
I will!

**Comment by tlvince** [comment]
:+1:

**Comment by johannesjo** [comment]
@tlvince just wanted to give some feedback: Unfortunately I won't be able to help out any time soon. I'm stuffed with work and my own projects deserve attention too. I still have it on my radar, but currently there are other more pressing issues to attend for me. I hope you understand.

**Comment by tlvince** [comment]
@johannesjo, no problem!

**Comment by tlvince** [comment]
We've a small trickle of users coming in from Google via wspringer's note. We've also been featured on [Angular-js.in](http://angular-js.in/angular-pouchdb/). Closing for now.
