### ISSUE TITLE
Bluebird.js Promises Support for $q

### ISSUE THREAD

**Issue by roblav96** [angular-pouchdb/angular-pouchdb#80]
By any chance would this amazing plugin work if I used
https://github.com/mattlewis92/angular-bluebird-promises
with
https://github.com/petkaantonov/bluebird
?

The benchmark scores of bluebird compared to $q are unmatched. And it's so much easier to use.

**Comment by gustavohenke** [comment]
You can fork this repo, add angular-bluebird-promises in the Karma files list, and then run the tests.

If everything goes well, then that's a good sign that the libraries will work well together.

**Comment by tlvince** [comment]
Let us know if you make any progress with this :)

**Comment by angelxmoreno** [comment]
:+1:

**Comment by tlvince** [comment]
angular-bluebird-promises mentions it's a drop-in replacement for `$q`, so I would assume it should "just work". Feel free to open a new issue if there's something angular-pouchdb could/should be doing to support it.
