### ISSUE TITLE
pouchDB() result is not $q promise

### ISSUE THREAD

**Issue by Ti-webdev** [angular-pouchdb/angular-pouchdb#81]
... and any chain of this not run $digest()...

pouchDB('mydb').then()...

**Comment by tlvince** [comment]
No, because it returns a wrapped PouchDB instance. Any method on the instance will return a promise.

```js
var db = pouchDB('mydb')
db.info().then()
```

**Comment by Ti-webdev** [comment]
May be replace promises methods (then, catch, ...) of instance?

**Comment by tlvince** [comment]
Oh I see what you mean:

```js
PouchDB('db').then(function() { console.log(arguments) })
// => Arguments (1)
// 0 i {__opts: {}, auto_compaction: undefined, prefix: "_pouch
```

I wasn't aware that was supported; I've always used it synchronously and the docs don't mention it. Curious how you use it though? I guess it's useful if you're already in a promise chain. But yeah, lets add that, why not.

**Comment by Ti-webdev** [comment]
I use it for remote database. In this case PouchDB check remote database.
PouchDB also added "then" and "catch" methods to instance object:
https://github.com/pouchdb/pouchdb/blob/master/lib/constructor.js#L180

**Comment by tlvince** [comment]
NB this has been [deprecated in PouchDB v5.4.0](https://pouchdb.com/2016/06/06/pouchdb-5.4.0.html):

> Deprecation #3: new PouchDB(dbName, callback)
