### ISSUE TITLE
bug in the npm scripts block

### ISSUE THREAD

**Issue by angelxmoreno** [angular-pouchdb/angular-pouchdb#86]
When I try to do 
```sh
npm install angular-pouchdb
```
I get the following error:
<img width="892" alt="screen shot 2015-12-09 at 11 46 38 pm" src="https://cloud.githubusercontent.com/assets/363479/11715013/7402e0e8-9f0c-11e5-8ad5-ac87754c33d2.png">

**Comment by marduke182** [comment]
Any plan to fix this, I could help if is needed? I am migrating my application from bower to npm and this is the only one library that not allow me to do it.

Thank you very much.

**Comment by marduke182** [comment]
Thanks. Very fast :)
