### ISSUE TITLE
Issue with Karma tests getting stuck

### ISSUE THREAD

**Issue by Sturgelose** [angular-pouchdb/angular-pouchdb#87]
Hello,

I'm trying to setup Karma integration tests of my code with PouchDB and I'm using this module in order to make it easier.

The thing is that if I run the code manually in the computer it works properly, but when I run it in side Karma, it's impossible to make it run. It gets stuck with the promise that should come back from pouchDB and times out.

It's exactly the same problem described in http://stackoverflow.com/questions/26328200/how-do-i-resolve-a-q-when-promise-in-unit-tests

 There they provide a solution, that as I see, is the same as you are doing in this repo when you are running tests of this library. However, try to add angular-pouchdb to be called from another service and debug this, and it's impossible to make this work.

Any advice on this? I'm not an expert in Karma and promises, neither in Jasmine, but maybe some info could help me a lot.

Thanks!

**Comment by tlvince** [comment]
Unfortunately, I've never found a good solution for this. PouchDB uses native promises, which use their own scheduler ("the microtask queue") separate from Angular's `evalAsync` queue. Injecting `ngMock` appears to interfere with the native scheduler somehow, which causes its promises never to resolve ("get stuck"); the usual `$rootScope.$apply` (to flush the queue) doesn't work here as PouchDB does not use Angular's scheduler.

The only workaround I've found is to not inject `ngMock` and to instead handle `$injector` manually, e.g.:

```js
describe('Working Q when tests', function() {
  var pouchdb;
  beforeEach(function() {
    var $injector = angular.injector(['ng', 'test']);
    var pouchDB = $injector.get('pouchdb');
    pouchdb = pouchDB('db');
  });

  it('should resolve a promise', function(done) {
    pouchdb.info()
      .then(function(info) {
        expect(info).toBeDefined();
      })
      .finally(done);
  });
});
```

Sorry to not offer a better solution to this. If you come across a better solution, please let me know.

**Comment by gustavohenke** [comment]
Additionally, the workaround we found for my issue may be applicable for your issue as well, @Sturgelose.

See #57 and http://stackoverflow.com/questions/32051825/external-promises-never-finish-in-unit-tests-with-ngmock

**Comment by tlvince** [comment]
The workaround suggested there was to spam `$rootScope.$digest`, e.g.:

```js
it('should wrap destroy', function(done) {
  var interval = $window.setInterval($rootScope.$digest.bind())
  db.destroy()
    .then(shouldBeOK)
    .then($window.clearInterval.bind(null, interval))
    .catch(shouldNotBeCalled)
    .finally(done)
})
```

… though it's ugly :wink:

**Comment by tlvince** [comment]
NB, it'd be nice to document these workarounds in the readme. Reopening.

**Comment by Sturgelose** [comment]
I also opened the issue in PouchDB official repository. Seems that as we say here, the issue comes from Angular. There I have better description of the issue, and yes, my way is to have an Interval every 30 ms, and it flushes the cache everytime. I also check for the HTTP calls, and flush them when needed...
https://github.com/pouchdb/pouchdb/issues/4657


Doing a small search, seems that this issue, will be fixed in Angular 2.0, so I hope that then we will be able to much easier testing!

**Comment by tlvince** [comment]
Thanks for the diagnosing on this. Would you be able to summarise the issue and add it to the readme?

**Comment by Sturgelose** [comment]
@tlvince, I will try to write down all what I've found out about the topic (also the different solutions that have been purposed)

As a small summary here for all the people: All fails because PouchDb uses as a promise library 'lie' and AngularJS uses a custom version of Q called '$q'. When testing, NgMock uses '$q' to setup the flushing of the async calls queue for the promises from other systems transformed to $q using `$q.when`. 
However, PouchDB uses a different library which has its own timer, which works without the digest queue of AngularJS and then it doesn't process the queue.

Solutions:
* Spam $rootScope.$apply() : this will make the async queue to be processed bit by bit. It can be done with an interval caller, but is really slow.... (Kinda works)
https://github.com/pouchdb/pouchdb/issues/4657#issuecomment-164894385
* Do not inject ngMock and to instead handle $injector manually: This way, the testing mocked tools should be working and we can still assert. Though if you need to use $httpBackend, or any ngMock tool, it worn't work well... 
https://github.com/angular-pouchdb/angular-pouchdb/issues/87#issuecomment-166241145
* (Found somewhere in the internet) Replace 'lie' for $q': Because both use the A+ standard, we should be able to replace lie in PouchDB for $q from angular. However, haven't been able to do so, as I don't really know how to replace them....
https://github.com/pouchdb/pouchdb/issues/4657#issuecomment-164874752

So in sum, the main origin of the problem is the AngularJS architecture for the digest loop. The big fix will come in AngularJS 2.0, where they have set it up so you can swap digest libraries and also they follow more the A+ starndards: https://docs.google.com/document/d/1ksBjyCgwuiEUGn9h2NYQGtmQkP5N9HbehMBgaxMtwfs/edit

Hope this is useful! (Will try to extend it a bit more if needed, though this should be okay)
Also, realized that if using pouchdb-find module, this module doesn't wrap it with $q.when! I just added it in a line in the code of this library and works well then :)

**Comment by tlvince** [comment]
That's great. Thanks. I'll add this to the readme.

**Comment by tlvince** [comment]
(Regarding `pouchdb-find`, you have to tell `angular-pouchdb` to also wrap its methods. See [Does this work with PouchDB plugins?](https://github.com/angular-pouchdb/angular-pouchdb/tree/193867022d8afa201cd2386cea68a5ef6df99bb4#does-this-work-with-pouchdb-plugins).)

**Comment by Sturgelose** [comment]
@tlvince thanks! Really useful! Didn't see that :D

**Comment by Sturgelose** [comment]
@tlvince, one comment regarding to disable ngMocks, is that then when you run it and it's an app with interface, it can't load the $rootElementProvider. So this solution would only be useful if you want to test pouchDB directly.

```
Unknown provider: $rootElementProvider <- $rootElement <- $location <- $urlRouter <- $state
```

**Comment by tlvince** [comment]
Are you testing a directive/something that uses a template?

**Comment by Sturgelose** [comment]
The module itself is for Ionic Framework / Cordova app, so the service shouldn't show a template, but eventually it would be...
