### ISSUE TITLE
Usage with Webpack

### ISSUE THREAD

**Issue by ColadaFF** [angular-pouchdb/angular-pouchdb#92]
Hi there.

I tried to use this with webpack and I get the error that "$window.PouchDB is not defined", so I went to the code and discovered this: 
```javascript
return function pouchDB(name, options) {
        var db = new $window.PouchDB(name, options);
        return wrapMethods(db, self.methods);
};
```

It seems like when I do this:
```javascript
require('pouchdb');
```
is not working, because webpack doesn't put the modules on the ```window```global object.

The only way to get this working is installing the expose loader on the project and shim PouchDB module, like this: 
```javascript
require('expose?PouchDB!pouchdb'); 
```

So, it would be great if you can add that to the docs  😄

Thanks!

**Comment by tlvince** [comment]
Thanks!

**Comment by sckoh** [comment]
I'm getting inherits is not a function when I expose PouchDB and I have no idea why
