### ISSUE TITLE
Cloudant ask to upgrade to Pouchdb >= 5.2.0

### ISSUE THREAD

**Issue by schobbent** [angular-pouchdb/angular-pouchdb#99]
My application uses cloudant as database service, and [pouchdb 5.1.0](https://github.com/pouchdb/pouchdb/releases/download/5.1.0/pouchdb-5.1.0.js) had some issues with the cloudant service : 

The first time a user connect on you website / app, pouchdb do a "setup". While that setup, PouchDB send some HTTP requests. One of that request is about bulk_get. But a ad setup of the request (missing authorization header in the http requet) cause the opening of a Dialog asking "Username / password.

Like this : http://i.stack.imgur.com/DRQt5.png

It was caused by a bad header request sent at line #1191 of pouchdb-5.1.0.js

```
      ajax({}, {
        headers: host.headers, // <------ This line has been removed in pouchdb 5.2.0
        url: genDBUrl(host, '_bulk_get' + paramsToStr(params)),
        method: 'POST',
        body: { docs: opts.docs}
      }, cb);
```

When I forced pouchdb to upgrade to 5.3.2, the problem was solved.

On my fork of angular-pouchd, branch "[fix-cloudant-dialog-problem](https://github.com/schobbent/angular-pouchdb/tree/fix-cloudant-dialog-problem)" I setuped the test with karma, and changed in bower.json 

`
"pouchdb": "~5.3.2"
`

And in my application now works fine :).

So I think that upgrading to 5.3.2 would be nice, and all the tests in karma passes, so... maybe more people should run the tests, and angular-pouchdb master branch should upgrade to 5.3.2 too ?

**Comment by tlvince** [comment]
Thanks for the great investigative work on this. I've pushed a [new release](https://github.com/angular-pouchdb/angular-pouchdb/releases).
